client-address
ALementa/superhero-shop pull request #1
Opened 2022-05-18 09:18 UTC by Dianadel25

Зробила блок. Передивіться будь ласка

2022-05-18 17:37 UTC, ALementa commented
Вже дивлюсь, але чесно кажучи не зовсім в'їхав що робити далі...

2022-05-18 19:14 UTC, ALementa commented on style.css
> +body{
Боді видаліть зі стилів, стилі тільки для блоку client-addres

2022-05-18 19:15 UTC, ALementa commented on style.css
> +body{
Боді видаліть зі стилів, стилі тільки для блоку client-addres

2022-05-18 21:20 UTC, Dianadel25 commented
Ну якщо там в роботі немає ніяких помилочок, то думаю можна мержити цю гілку, хоча думаю буде краще спитатись в Віталія

2022-05-18 21:31 UTC, ALementa commented
Так, сьогодні зустрічалися, підкажіть він наче вчора Вам казав зробити на мобільну версію по центру чи на всю ширину, Ви цього не робили?

2022-05-18 22:09 UTC, ALementa commented
Можете мені скинути текст завдання, бо я його не бачив))

2022-05-18 22:22 UTC, ALementa requested changes

2022-05-18 22:22 UTC, ALementa commented on style.css
> +body{
Привіт від Віталія- не було завдання: прописати стилі для боді))

2022-05-18 22:22 UTC, ALementa commented on style.css
> +  max-width: 140px;
Чому обмеження 140 пікселів?

2022-05-18 22:22 UTC, ALementa commented on tech/tech.html
> +          <div class="client-address__content">
Я би розділив адрес та телефон, адрес однією строкою, а телефон іншою без списка

2022-05-18 22:22 UTC, ALementa commented on style.css
> +  display: grid;
А можна як Віталій казав не використовувати Грід?

2022-05-19 07:21 UTC, Dianadel25 commented on style.css
> +body{
так я також думала що напевне не потрібно, але не знала чи всовувати всі стилі для тексту в певний блок. Дивилась на всі тексти, які є на макеті, то ці використовувався найчастіше

2022-05-19 07:22 UTC, Dianadel25 commented on style.css
> +  max-width: 140px;
з цим щось придумаю

2022-05-19 07:23 UTC, Dianadel25 commented on tech/tech.html
> +          <div class="client-address__content">
не зовсім розумію навіщо так робити

2022-05-19 07:24 UTC, Dianadel25 commented on style.css
> +  display: grid;
Так там можна не використовувати його. Просто вирішила спробувати, хоча може переробити флексом. То треба буде ним переробляти?

2022-05-19 07:28 UTC, Dianadel25 commented on style.css
> +  display: grid;
![Снимок](https://user-images.githubusercontent.com/102838845/169236612-08dbf890-ea1b-4d03-a7b5-4c6ed78e1931.PNG)

2022-05-19 07:34 UTC, Dianadel25 commented on style.css
> +  max-width: 140px;
можу забрати обмеження і тоді воно завжди буде ставати в блоці справа зверху, ось так це виглядає без обмеження, нормально буде?
![апва](https://user-images.githubusercontent.com/102838845/169237712-c8aaca40-fea1-443f-a380-10b5b173d846.PNG)

2022-05-19 07:36 UTC, Dianadel25 commented on style.css
> +body{
то мені всовувати стилі тексту туди, чи там хтось інший має по цьому боді завдання?

2022-05-19 11:47 UTC, ALementa commented on style.css
> +body{
Так боді буде робити хтось інший, наша задача зверстати конкретний блок, тому що ми не знаємо де його будуть використовувати, можливо в іншому сайті де в боді будуть інші шрифти

2022-05-19 12:04 UTC, ALementa commented on tech/tech.html
> +          <div class="client-address__content">
Ну це суто за моєю логікою, я представляю об'єкт у якого 3 поля 1) Ім'я 2)Адреса 3)Телефон, Наприклад чолов'яга змінив номер телефону, але не переїхав, адреса та сама а номер інший, треба змінити номер на сайті, або задати інший шрифт. Але це суто моя логіка, можна  залишити вашу логіку, але замість списку зробити строку яка при збільшенні ширини блоку буде заповнювати всю ширину, бо ми також не знаємо яка буде ширина блоку, і яка буде довжина тексту, ми не знаємо з якої країни буде чоловік...

2022-05-19 12:13 UTC, ALementa commented on tech/tech.html
> +          <div class="client-address__content">
![1client-address](https://user-images.githubusercontent.com/99717125/169290538-d27e3ceb-8f9a-4787-862e-10bdbf9e8539.png)
я собі уявляю це так

2022-05-19 23:03 UTC, ALementa approved these changes
Ок

2022-05-19 23:03 UTC, merged